#!/usr/bin/env bash
#
# link-happier-local.sh — install/remove a `happier` command that runs THIS
# repo's local apps/cli build (Node 24, data dir ~/.happier), bypassing hstack.
#
# Why a wrapper (not a copy or bare symlink): bin/happier.mjs imports sibling
# files relatively and needs dist/ next to it, so it must run IN PLACE; and it
# must run under Node 24 (node-pty rejects Node >= 25).
#
# Analogous to `yarn link:dev`, but targets the stable ~/.happier home (not
# ~/.happier-dev) and pins Node 24.
#
# Usage:
#   scripts/link-happier-local.sh                 # install -> ~/.local/bin/happier
#   scripts/link-happier-local.sh --name happier-local
#   scripts/link-happier-local.sh --dir "$HOME/bin"
#   scripts/link-happier-local.sh uninstall
#
set -euo pipefail

action="install"
name="happier"
dir="$HOME/.local/bin"

while [ $# -gt 0 ]; do
  case "$1" in
    install|uninstall) action="$1" ;;
    --name) name="$2"; shift ;;
    --name=*) name="${1#*=}" ;;
    --dir) dir="$2"; shift ;;
    --dir=*) dir="${1#*=}" ;;
    -h|--help) echo "usage: $0 [install|uninstall] [--name NAME] [--dir DIR]"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cli_root="$(cd "$script_dir/.." && pwd)"
cli_entry="$cli_root/bin/happier.mjs"
target="$dir/$name"

if [ "$action" = "uninstall" ]; then
  rm -f "$target" && echo "removed $target"
  exit 0
fi

[ -f "$cli_entry" ] || { echo "error: $cli_entry not found (run from apps/cli)" >&2; exit 1; }
[ -f "$cli_root/dist/index.mjs" ] || echo "note: dist not built yet — run: (cd $cli_root && yarn build)" >&2

mkdir -p "$dir"
# Always write a FRESH file. Never write through an existing hard/symlink: if
# $target were hardlinked to a repo source (e.g. bin/happier.mjs), `cat >` would
# clobber that source via the shared inode.
rm -f "$target"
cat > "$target" <<EOF
#!/bin/bash
# happier -> local apps/cli build (data dir ~/.happier). Generated by link-happier-local.sh.
# Revert: rm "$target"        Stack version stays available as: hstack happier ...
CLI_ENTRY="$cli_entry"
if command -v mise >/dev/null 2>&1; then exec mise exec node@24 -- node "\$CLI_ENTRY" "\$@"; fi
exec node "\$CLI_ENTRY" "\$@"
EOF
chmod +x "$target"

echo "installed: $target"
echo "  -> $cli_entry   (Node 24 via mise; data dir ~/.happier)"
case ":$PATH:" in
  *":$dir:"*) : ;;
  *) echo "WARNING: $dir is not on your PATH — add it, or invoke with the full path." >&2 ;;
esac
echo "try:    $name auth login --skip-account-safety-code"
echo "revert: $0 uninstall"
